#!/bin/sh
# 99-nss-athena - 雅典娜 NSS + 点阵屏开机配置

# 关闭与 NSS 冲突的 offload
uci set network.@device[0].packet_steering=0
uci set network.@device[0].flow_offloading=0
uci set network.@device[0].flow_offloading_hw=0
uci commit network

# 时区
uci set system.@system[0].zonename='Asia/Shanghai'
uci set system.@system[0].timezone='CST-8'
uci commit system

# 启用 athena_led 开机自启
/etc/init.d/athena_led enable
/etc/init.d/athena_led start

exit 0
